allowBuilds:
  msgpackr-extract: true
  tree-sitter: true
  tree-sitter-bash: true
  tree-sitter-pwsh: true
patchedDependencies:
  tree-sitter@0.25.0: patches/tree-sitter@0.25.0.patch
  tree-sitter-pwsh@0.38.0: patches/tree-sitter-pwsh@0.38.0.patch
